@startuml C3 Component - Module View (zoom-in)
!include <C4/C4_Component>

!define ICONS ./plantuml-icon-font-sprites
!include ICONS/font-awesome-5/mobile_alt.puml

AddElementTag("finance_tracking", $fontColor = "#000000", $bgColor = "#05B8E6")
AddElementTag("banks", $fontColor = "#000000", $bgColor="#05E67E")
AddElementTag("events_bus", $fontColor="#FFFFFF", $bgColor = "#0027EB")
AddRelTag("async", $textColor = "$ARROW_FONT_COLOR", $lineColor = "$ARROW_COLOR",$lineStyle = DashedLine())

System_Boundary(c1, "Savify") {
    Boundary(api, "Savify API") {
        Component(web_api, "API", ".NET Core API")

        Boundary(finance_tracking, "Finance Tracking Module") {
            Component(finance_tracking_infrastructure, "FinanceTracking.Infrastructure", ".NET Library", $tags="finance_tracking")
            Component(finance_tracking_application, "FinanceTracking.Application", ".NET Library", $tags="finance_tracking")
            Component(finance_tracking_domain, "FinanceTracking.Domain", ".NET Library", $tags="finance_tracking")
            Component(finance_tracking_integration_events, "FinanceTracking.IntegrationEvents", ".NET Library", $tags="finance_tracking")
            ComponentDb(finance_tracking_data, "FinanceTracking data", "database schema", $tags="finance_tracking")
        }

        Boundary(banks, "Banks Module") {
            Component(banks_infrastructure, "Banks.Infrastructure", ".NET Library", $tags="banks")
            Component(banks_application, "Banks.Application", ".NET Library", $tags="banks")
            Component(banks_domain, "Banks.Domain", ".NET Library", $tags="banks")
            Component(banks_integration_events, "Banks.IntegrationEvents", ".NET Library", $tags="banks")
            ComponentDb(banks_data, "Banks data", "database schema", $tags="banks")
        }

        ComponentQueue(events_bus, "Events Bus", "In memory", $tags="events_bus")
    }
}

Rel_D(web_api, finance_tracking_application, "Uses")
Rel_D(web_api, banks_application, "Uses")
Rel_D(web_api, finance_tracking_infrastructure, "Uses")
Rel_D(web_api, banks_infrastructure, "Uses")


Rel_U(finance_tracking_application, finance_tracking_domain, "Depends on")
Rel(finance_tracking_application, finance_tracking_data, "Reads from", "SQL")
Rel(finance_tracking_application, finance_tracking_integration_events, "Uses")
Rel(finance_tracking_application, banks_integration_events, "Uses")
Rel_U(finance_tracking_infrastructure, finance_tracking_application, "Depends on")
Rel_U(finance_tracking_infrastructure, finance_tracking_domain, "Depends on")
Rel(finance_tracking_infrastructure, finance_tracking_data, "Reads from | Writes to", "EntityFramework|SQL")
Rel(finance_tracking_infrastructure, events_bus, "Publish events to | subscribes on", "async", $tags="async")

Rel_U(banks_application, banks_domain, "Depends on")
Rel(banks_application, banks_data, "Reads from", "SQL")
Rel(banks_application, banks_integration_events, "Uses")
Rel(banks_application, finance_tracking_integration_events, "Uses")
Rel_U(banks_infrastructure, banks_application, "Depends on")
Rel_U(banks_infrastructure, banks_domain, "Depends on")
Rel(banks_infrastructure, banks_data, "Reads from | Writes to", "EntityFramework|SQL")
Rel(banks_infrastructure, events_bus, "Publish events to | subscribes on", "async", $tags="async")

SHOW_LEGEND()
@enduml
